name: call-variants
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - biopython=1.76
  - bcbiogff=0.6.*
  - pysam=0.16.*
  - bwa=0.7.*
  - samtools=1.12
  - samclip=0.4.*
  - blast=2.11.*
  - freebayes=1.3.*
  - vt=0.57721
  - snpeff=5.0
